# Generated by Django 3.2.4 on 2021-07-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Rate',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
